# -*- coding: utf-8 -*-
"""trabajosinnombrar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fyw3Erpo7HxnjrCPyLRDEGEEilyl9GYW
"""

"""
Proyecto: Análisis de portafolios de inversión por Simulación Monte Carlo

"""
# %%writefile app.py

# ==== 1 Importar librerías ====
import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from scipy.stats import norm
import sys
import subprocess
import threading
import time
import io
import math
from typing import List
from scipy.optimize import minimize
from datetime import datetime

# Configuración de página
st.set_page_config(page_title="ESCENARIOS DE INVERSIÓN: DESCUBRE TU PERFIL INVERSOR. ", layout="wide")

# ==========================================
# 1. CUESTIONARIO Y FILTRO DE CONOCIMIENTO
# ==========================================
st.title("Determina tu perfil inversor.")
with st.sidebar:
    st.header("Perfil del Inversor")
    nombre = st.text_input("Nombre completo")
    edad = st.number_input("Edad", 18, 100, 25)
    monto = st.number_input("Cantidad a invertir (USD)", 1000, 1000000, 10000)
    tiempo = st.slider("Tiempo de inversión (Años)", 1, 10, 5)

    st.subheader("Filtro de Conocimiento")
    p1 = st.radio("Inflación: $100 al 2% con inflación del 3%, ¿compras más o menos?", ["Más", "Menos", "Igual"])
    p2 = st.radio("Riesgo-Retorno: Inversión garantizada 20% mensual sin riesgo es:", ["Muy probable", "Estafa/Error", "Normal"])
    p3 = st.radio("Diversificación: ¿Una sola acción es más segura que un ETF?", ["Sí", "No"])
    p4 = st.radio("Estadística: Retorno 10% y Volatilidad 25%, ¿puedo perder dinero?", ["Sí", "No"])

    # Lógica de Puntaje
    score = 0
    if p1 == "Menos": score += 1
    if p2 == "Estafa/Error": score += 1
    if p3 == "No": score += 1
    if p4 == "Sí": score += 1

    # Determinación de Perfil
    if score <= 1:
        perfil = "Conservador"
        tickers_sugeridos = ["BND", "TIP", "GLD", "VIG","VTI"] # Bonos, Oro, Dividendos
    elif score <= 3:
        perfil = "Balanceado"
        tickers_sugeridos = ["SPY", "VEU", "BND", "VNQ","IEMG"] # S&P500, Global, Inmuebles
    else:
        perfil = "Arriesgado"
        tickers_sugeridos = ["QQQ", "VWO", "BTC-USD", "SMH","NVDA","ETH-USD"] # Tech, Emergentes, Crypto

    st.success(f"Perfil Determinado: **{perfil}**")
    st.info(f"Nivel de conocimiento Financiero-estadistico: {score}/4")

# ==========================================
# 2. SELECCIÓN DE ACTIVOS Y DATOS
# ==========================================
st.header(f" Análisis del Portafolio Sugerido {perfil}")
tickers_input = st.text_input("Activos (separaDOS por coma):", ",".join(tickers_sugeridos))
tickers = [t.strip() for t in tickers_input.split(",")]

@st.cache_data
def get_data(tickers):
    data = yf.download(tickers, start="2019-01-01")['Close']
    return data

data = get_data(tickers)
returns = data.pct_change().dropna()

if not data.empty:
    returns = data.pct_change().dropna()
    mu = returns.mean() * 252
    sigma = returns.std() * np.sqrt(252)
    cov_matrix = returns.cov() * 252
    
    # Visualización de Crecimiento Relativo
    st.subheader("📈 Crecimiento Relativo (Base 100 desde 2019)")
    data_norm = (data / data.iloc[0]) * 100
    st.line_chart(data_norm)

    # --- BOTÓN DE OPTIMIZACIÓN AUTOMÁTICA ---
    st.divider()
    st.subheader("⚖️ Optimización de Pesos")
    
    col_opt, col_pesos = st.columns([1, 2])
    
    with col_opt:
        st.write("Calcula la distribución ideal para el menor riesgo posible.")
        if st.button("🚀 Optimizar para Mínima Varianza"):
            n = len(tickers)
            def p_vol(weights):
                return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
            
            constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})
            bounds = tuple((0, 1) for _ in range(n))
            init_guess = n * [1./n]
            
            optimized = minimize(p_vol, init_guess, method='SLSQP', bounds=bounds, constraints=constraints)
            st.session_state['pesos'] = optimized.x
            st.success("¡Optimización completada!")
        else:
            if 'pesos' not in st.session_state:
                st.session_state['pesos'] = np.array([1/len(tickers)] * len(tickers))

    pesos = st.session_state['pesos']
    pesos_df = pd.DataFrame({'Activo': tickers, 'Peso %': pesos * 100})
    
    with col_pesos:
        fig_pie = px.pie(pesos_df, values='Peso %', names='Activo', title="Distribución del Capital")
        st.plotly_chart(fig_pie, use_container_width=True)

# Estadísticas Anualizadas
mu = returns.mean() * 252
sigma = returns.std() * np.sqrt(252)
sharpe = mu / sigma

col1, col2 = st.columns(2)
with col1:
    st.subheader("📊 Estadísticas Históricas")
    stats_df = pd.DataFrame({"Retorno Anual (μ)": mu, "Volatilidad (σ)": sigma, "Eficiencia (Sharpe)": sharpe})
    st.table(stats_df)

with col2:
    st.subheader("🔥 Mapa de Correlaciones")
    fig_corr = px.imshow(returns.corr(), text_auto=True, color_continuous_scale='RdBu_r')
    st.plotly_chart(fig_corr, use_container_width=True)

# ==========================================
# 3. ESCENARIOS DE ESTRÉS
# ==========================================
st.divider()
st.header("SIMULADOR DE CRISIS GLOBAL")
st.write("Selecciona un evento para ver la resiliencia de tu portafolio:")

c_s1, c_s2, c_s3, c_s4 = st.columns(4)
shock_mu = 0
shock_sigma = 1
shock_corr = 0
nombre_evento = "Normal"

with c_s1:
    if st.button("Guerra Mundial"):
            shock_mu, shock_sigma, shock_corr, nombre_evento = -0.15, 1.8, 0.4, "Guerra Mundial"
            st.warning("Efecto: Caída en retornos y alta correlación.")
with c_s2:
    if st.button("Pandemia"):
            shock_mu, shock_sigma, shock_corr, nombre_evento = -0.10, 2.2, 0.2, "Pandemia"
            st.warning("Efecto: Volatilidad extrema.")
with c_s3:
    if st.button("🏗️ Aranceles"):
            shock_mu, shock_sigma, nombre_evento = -0.06, 1.3, "Choque Arancelario"
            st.warning("Efecto: Reducción de retornos en exportación.")
with c_s4:
    if st.button("🔄 Reset"):
            shock_mu, shock_sigma, shock_corr, nombre_evento = 0, 1, 0, "Normal"

st.write(f"Escenario Activo: **{nombre_evento}**")
   
# ==========================================
# 4. SIMULACIÓN MONTE CARLO (1 AÑO)
# ==========================================

# Ajuste de parámetros por Stress Test
    mu_sim = p_ret_hist + shock_mu
    # Simplificación: incrementamos la volatilidad y forzamos correlación positiva en crisis
    vol_sim = p_vol_hist * shock_sigma + (shock_corr * 0.1)

    simulaciones = 1000
    dias = 252
    resultados = np.zeros((dias, simulaciones))

    for i in range(simulaciones):
        rets_sim = np.random.normal(mu_sim/dias, vol_sim/np.sqrt(dias), dias)
        resultados[:, i] = monto_inicial * (1 + rets_sim).cumprod()

    # Gráficos de resultados
    st.subheader(f"📊 Proyección a 1 año: Escenario {nombre_evento}")
    
    col_g1, col_g2 = st.columns([2, 1])
    
    with col_g1:
        fig_mc = go.Figure()
        for i in range(100): # Mostrar 100 trayectorias
            fig_mc.add_trace(go.Scatter(y=resultados[:, i], mode='lines', opacity=0.3, showlegend=False))
        st.plotly_chart(fig_mc, use_container_width=True)

    with col_g2:
        precios_finales = resultados[-1, :]
        fig_hist = px.histogram(precios_finales, nbins=10, title="Distribución de Valor Final")
        st.plotly_chart(fig_hist, use_container_width=True)

# ==========================================
# 5. DASHBOARD DE INTERPRETACIÓN
# ==========================================
st.divider()
st.header("Informe del inversor")

peor_escenario = np.percentile(precios_finales, 5) - monto_inicial
    mejor_escenario = np.percentile(precios_finales, 95) - monto_inicial
    prob_perdida = (np.sum(precios_finales < monto_inicial) / simulaciones) * 100

    col_res1, col_res2 = st.columns(2)
    
    with col_res1:
        st.subheader("🚦 Semáforo de Riesgo")
        if prob_perdida > 40:
            st.error(f"RIESGO CRÍTICO: Hay un {prob_perdida:.1f}% de probabilidad de terminar en pérdida bajo este escenario.")
        elif prob_perdida > 20:
            st.warning(f"RIESGO MEDIO: Probabilidad de pérdida del {prob_perdida:.1f}%.")
        else:
            st.success(f"RIESGO BAJO: Portafolio resiliente con solo {prob_perdida:.1f}% de prob. de pérdida.")

    with col_res2:
        st.subheader("🔍 Traductor de Métricas")
        st.write(f"**Incertidumbre:** Tu volatilidad ajustada es de **{vol_sim:.2%}**. Esto significa que el valor de tu dinero podría oscilar violentamente en un año.")
        st.write(f"**Pronóstico:** En el peor 5% de los casos, podrías perder **${abs(peor_escenario):,.2f}**.")
        st.write(f"**Eficiencia:** Tu Ratio de Sharpe indica qué tan bien se te paga por el susto que pasas al invertir.")

else:
    st.warning("Por favor, ingresa tickers válidos para comenzar el análisis.")

from fpdf import FPDF
import base64

def generar_pdf(nombre, perfil, score, monto, p_ret, p_vol, evento, prob_p, peor_esc):
    pdf = FPDF()
    pdf.add_page()
    
    # Encabezado
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Reporte de Simulación Financiera - Proyecto Semillero", ln=True, align='C')
    pdf.ln(10)
    
    # Datos del Usuario
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt=f"Inversionista: {nombre}", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(200, 8, txt=f"Perfil Determinado: {perfil} (Sabiduria: {score}/4)", ln=True)
    pdf.cell(200, 8, txt=f"Capital Inicial: ${monto:,.2f} USD", ln=True)
    pdf.ln(5)
    
    # Estadísticas del Portafolio
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Métricas de Desempeño Histórico:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(200, 8, txt=f"- Retorno Esperado Anual: {p_ret:.2%}", ln=True)
    pdf.cell(200, 8, txt=f"- Volatilidad (Riesgo): {p_vol:.2%}", ln=True)
    pdf.ln(5)
    
    # Resultados del Escenario de Estrés
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt=f"Análisis de Resiliencia (Escenario: {evento})", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(200, 8, txt=f"- Probabilidad de terminar en pérdida: {prob_p:.1f}%", ln=True)
    pdf.cell(200, 8, txt=f"- Máxima pérdida estimada (peor 5%): ${abs(peor_esc):,.2f}", ln=True)
    pdf.ln(10)
    
    # Conclusión
    pdf.set_font("Arial", 'I', 11)
    msg = "Este reporte es una simulacion basada en datos historicos y metodos de Monte Carlo. No constituye asesoria financiera legal."
    pdf.multi_cell(0, 10, txt=msg)
    
    return pdf.output(dest='S').encode('latin-1')

# --- BOTÓN DE DESCARGA EN LA INTERFAZ ---
st.divider()
st.subheader("📥 Exportar Resultados")

pdf_bytes = generar_pdf(
    nombre, perfil, score_conocimiento, monto_inicial, 
    p_ret_hist, p_vol_hist, nombre_evento, prob_perdida, peor_escenario
)

st.download_button(
    label="📄 Descargar Reporte en PDF",
    data=pdf_bytes,
    file_name=f"Reporte_Inversion_{nombre}.pdf",
    mime="application/pdf"
)
