# -*- coding: utf-8 -*-
"""trabajosinnombrar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fyw3Erpo7HxnjrCPyLRDEGEEilyl9GYW
"""


# %%writefile app.py


import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go 
from datetime import datetime, timedelta
from fpdf import FPDF
from scipy.optimize import minimize


# Configuración de página
st.set_page_config(page_title="DACS-Quant: Gestión de Portafolios", layout="wide")

#
defaults = {"nombre": "Inversionista", "edad": 25, "monto": 10000, "tiempo": 5, "perfil": None,  "score": 0, "tickers_sugeridos": [], 
            "generado": False, "shock_mu": 0.0, "shock_sigma": 1.0, "shock_corr": 0.0, "nombre_evento": "Normal"}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value

# funciones

@st.cache_data(ttl=3600)
def get_data(tickers):

    try:

        data = yf.download(tickers, start="2019-01-01", progress=False, auto_adjust=True)["Close"]
        return data
    except Exception as e:

        st.error(f"Error descargando datos: {e}")
        return pd.DataFrame()


def monte_carlo_vectorizado(monto_inicial, mu_sim, vol_sim, simulaciones=10000, dias=252):

    rets_sim = np.random.normal((mu_sim / dias), (vol_sim / np.sqrt(dias)), (dias, simulaciones)    )

    precios_simulados = (monto_inicial *(1 + rets_sim).cumprod(axis=0)    )

    return precios_simulados


def generar_pdf(nombre, perfil, score, monto, p_ret, p_vol, evento, prob_p, peor_esc):

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt="Reporte de Simulación Financiera", ln=True, align="C")
    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, txt=f"Inversionista: {nombre}", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.cell(200, 8, txt=f"Perfil: {perfil} | Score: {score}/4", ln=True)
    pdf.cell(200, 8, txt=f"Capital Inicial: ${monto:,.2f}", ln=True)
    pdf.ln(5)
    pdf.cell(200, 8, txt=f"Retorno Esperado: {p_ret:.2%}", ln=True)
    pdf.cell(200, 8, txt=f"Volatilidad: {p_vol:.2%}", ln=True)
    pdf.cell(200, 8, txt=f"Escenario: {evento}", ln=True)
    pdf.cell(200, 8, txt=f"Probabilidad de pérdida: {prob_p:.1f}%", ln=True)
    pdf.cell(200, 8, txt=f"VaR 95%: ${abs(peor_esc):,.2f}", ln=True)

    return pdf.output(dest="S").encode("latin-1")

# SIDEBAR

with st.sidebar:

    st.header("Perfil del Inversor")

    nombre = st.text_input("Nombre completo", value=st.session_state.nombre)
    st.session_state.nombre = nombre

    edad = st.number_input("Edad", min_value=18, max_value=100, value=st.session_state.edad)
    st.session_state.edad = edad

    monto = st.number_input("Cantidad a invertir (USD)", min_value=1000, max_value=1000000, value=st.session_state.monto)
    st.session_state.monto = monto

    tiempo = st.slider("Tiempo de inversión (años)", min_value=1, max_value=10, value=st.session_state.tiempo)
    st.session_state.tiempo = tiempo

    st.subheader("Filtro de Conocimiento")

    p1 = st.radio("Inflación: $100 al 2% con inflación del 3%, ¿compras más o menos?", ["Más", "Menos", "Igual"])

    p2 = st.radio("Riesgo-Retorno: Inversión garantizada 20% mensual sin riesgo es:", ["Muy probable", "Estafa/Error", "Normal"])

    p3 = st.radio("Diversificación: ¿Una sola acción es más segura que un ETF?", ["Sí", "No"])

    p4 = st.radio("Estadística: Retorno 10% y Volatilidad 25%, ¿puedo perder dinero?", ["Sí", "No"])

    if st.button("🚀 Generar Portafolio"):

        score = 0

        if p1 == "Menos":
            score += 1

        if p2 == "Estafa/Error":
            score += 1

        if p3 == "No":
            score += 1

        if p4 == "Sí":
            score += 1

        st.session_state.score = score

#Perfil

        if score <= 1:

            st.session_state.perfil = "Conservador"

            st.session_state.tickers_sugeridos = ["BND", "TIP", "GLD", "VIG", "VTI"]

        elif score <= 3:

            st.session_state.perfil = "Balanceado"

            st.session_state.tickers_sugeridos = ["SPY", "VEU", "BND", "VNQ", "IEMG"]

        else:

            st.session_state.perfil = "Arriesgado"

            st.session_state.tickers_sugeridos = ["VWO", "BTC-USD", "SMH", "NVDA", "ETH-USD"]

        st.session_state.generado = True

        st.success(f"Perfil Determinado: {st.session_state.perfil}")

        st.info(f"Score financiero: {st.session_state.score}/4")

# RESET

if st.button("🔄 Reiniciar"):

        for key in list(st.session_state.keys()):
            del st.session_state[key]

        st.rerun()

# CONTROL DE EJECUCIÓN

if not st.session_state.generado:

    st.title("📊 Simulador de Portafolios")
    st.info("Completa el formulario y presiona "  "'Generar Portafolio'")
    st.stop()

# VARIABLES PRINCIPALES

perfil = st.session_state.perfil
score = st.session_state.score

#ACTIVOS

st.title(f"Portafolio Sugerido: {perfil}")

tickers_input = st.text_input("Activos (separados por coma)", ",".join(st.session_state.tickers_sugeridos))

tickers = [t.strip() for t in tickers_input.split(",")]

# DATOS HISTÓRICOS

data = get_data(tickers)

if data.empty:
    st.error("No se pudieron descargar datos.")
    st.stop()
    
data = data.dropna(axis=1, how="all")
data = data.ffill()
data = data.dropna()

if data.empty:
    st.error("Datos inválidos.")
    st.stop()

returns = data.pct_change().dropna()

mu = returns.mean() * 252
sigma = returns.std() * np.sqrt(252)
cov_matrix = returns.cov() * 252

# GRÁFICO HISTÓRICO

st.subheader("📈 Comportamiento Histórico Relativo")

data_norm = (data / data.iloc[0]) * 100
fig_hist = go.Figure()

for col in data_norm.columns:
    fig_hist.add_trace(go.Scatter(x=data_norm.index, y=data_norm[col], mode="lines", name=col))

fig_hist.update_layout(template="plotly_dark", hovermode="x unified")

st.plotly_chart(fig_hist, use_container_width=True)

# OPTIMIZACIÓN

st.divider()
st.subheader("⚖️ Optimización de Pesos")

col_opt, col_pesos = st.columns([1, 2])

with col_opt:
    st.write(
        "Calcula la distribución ideal del portafolio "
        "para maximizar el Ratio Sharpe (mejor relación entre retorno y riesgo)."
    )

# Calcular rendimientos diarios
    price_column = "Adj Close" if "Adj Close" in data.columns else "Close"
    returns = data[price_column].pct_change().dropna()

# Calcular retornos esperados anualizados
    expected_returns = (returns.mean() * 252).values.flatten()

# Calcular matriz de covarianza anualizada
    cov_matrix = (returns.cov() * 252).values

    if st.button("Optimizar para Máximo Sharpe"):
        n = len(tickers)

        # Tasa libre de riesgo anual (puedes ajustarla según tu criterio)
        risk_free_rate = 0.05  # 5%

        # Función objetivo: negativo del Sharpe Ratio
        # Se utiliza negativo porque scipy.optimize.minimize() minimiza.
        def negative_sharpe(weights):
            # Retorno esperado del portafolio
            portfolio_return = np.dot(weights, expected_returns)

            # Volatilidad del portafolio
            portfolio_volatility = np.sqrt(
                np.dot(weights.T, np.dot(cov_matrix, weights))
            )

            # Evitar división por cero
            if portfolio_volatility == 0:
                return 1e6

            # Cálculo del Ratio Sharpe
            sharpe_ratio = (
                portfolio_return - risk_free_rate
            ) / portfolio_volatility

            # Retornamos el negativo para maximizar Sharpe
            return -sharpe_ratio

        # Restricción: la suma de los pesos debe ser 100%
        constraints = (
            {"type": "eq", "fun": lambda x: np.sum(x) - 1},
        )

        # Restricción de pesos entre 0% y 100% (sin ventas en corto)
        bounds = tuple((0, 1) for _ in range(n))

        # Pesos iniciales iguales
        init_guess = np.array([1 / n] * n)

        # Optimización
        optimized = minimize(
            negative_sharpe,
            init_guess,
            method="SLSQP",
            bounds=bounds,
            constraints=constraints
        )

        # Guardar pesos óptimos
        st.session_state.pesos = optimized.x

        # Calcular métricas del portafolio óptimo
        portfolio_return = np.dot(optimized.x, expected_returns)
        portfolio_volatility = np.sqrt(
            np.dot(optimized.x.T, np.dot(cov_matrix, optimized.x))
        )
        sharpe_ratio = (
            portfolio_return - risk_free_rate
        ) / portfolio_volatility

        # Guardar métricas en session_state (opcional)
        st.session_state.opt_return = portfolio_return
        st.session_state.opt_volatility = portfolio_volatility
        st.session_state.opt_sharpe = sharpe_ratio

        st.success("Optimización por Máximo Sharpe completada.")

    # Inicializar pesos si no existen
    if "pesos" not in st.session_state:
        st.session_state.pesos = np.array(
            [1 / len(tickers)] * len(tickers)
        )

    # DataFrame de resultados
    pesos = st.session_state.pesos
    pesos_df = pd.DataFrame({
        "Activo": tickers,
        "Peso %": pesos * 100
    })

    # Mostrar métricas si ya fueron calculadas
    if "opt_return" in st.session_state:
        st.divider()
        st.markdown("### 📈 Métricas del Portafolio Óptimo")
        st.write(
            f"**Retorno Esperado Anual:** "
            f"{st.session_state.opt_return:.2%}"
        )
        st.write(
            f"**Volatilidad Anual:** "
            f"{st.session_state.opt_volatility:.2%}"
        )
        st.write(
            f"**Ratio Sharpe:** "
            f"{st.session_state.opt_sharpe:.2f}"
        )

    st.divider()
    st.markdown("### 📊 Resultados Detallados")

    for _, row in pesos_df.iterrows():
        st.write(
            f"**{row['Activo']}:** "
            f"{row['Peso %']:.2f}%"
        )

with col_pesos:
    fig_pie = px.pie(
        pesos_df,
        values="Peso %",
        names="Activo",
        title="Distribución Óptima del Capital"
    )
    st.plotly_chart(fig_pie, use_container_width=True)

# ESTADÍSTICAS

sharpe = mu / sigma.replace(0, np.nan)

col1, col2 = st.columns(2)
with col1:
    st.subheader("📊 Estadísticas Históricas")
    stats_df = pd.DataFrame({"Retorno Anual":mu, "Volatilidad":sigma, "Sharpe":sharpe})
    st.table(stats_df)

with col2:
    st.subheader("🔥 Correlaciones")
    fig_corr = px.imshow(returns.corr(), text_auto=True, color_continuous_scale="RdBu_r")
    st.plotly_chart(fig_corr, use_container_width=True)

# ESCENARIOS DE ESTRÉS

st.divider()
st.header("Simulaciones")
c1, c2, c3, c4 = st.columns(4)

with c1:

    if st.button("Guerra Mundial"):
        st.session_state.shock_mu = -0.20
        st.session_state.shock_sigma = 1.8
        st.session_state.shock_corr = 0.4
        st.session_state.nombre_evento = "Guerra Mundial"

with c2:
    if st.button("Pandemia"):
        st.session_state.shock_mu = -0.12
        st.session_state.shock_sigma = 3.0
        st.session_state.shock_corr = 0.5
        st.session_state.nombre_evento = "Pandemia"

with c3:
    if st.button("Aranceles"):
        st.session_state.shock_mu = -0.05
        st.session_state.shock_sigma = 1.5
        st.session_state.shock_corr = 0.3
        st.session_state.nombre_evento = "Choque Arancelario"

with c4:
    if st.button("Reset Escenario"):
        st.session_state.shock_mu = 0.0
        st.session_state.shock_sigma = 1.0
        st.session_state.shock_corr = 0.0
        st.session_state.nombre_evento = "Normal"

shock_mu = st.session_state.shock_mu
shock_sigma = st.session_state.shock_sigma
shock_corr = st.session_state.shock_corr
nombre_evento = st.session_state.nombre_evento

st.write(f"Escenario activo: {nombre_evento}")

# MONTE CARLO

p_ret_hist = np.dot(pesos, mu)
p_vol_hist = np.sqrt(np.dot(pesos.T, np.dot(cov_matrix, pesos)))
mu_sim = p_ret_hist + shock_mu
vol_sim = (p_vol_hist * shock_sigma + (shock_corr * 0.1))

with st.spinner("Procesando simulaciones..."):

    resultados = monte_carlo_vectorizado(monto, mu_sim, vol_sim)

# GRÁFICOS MONTE CARLO

st.subheader(f"📊 Proyección a 1 año - {nombre_evento}")

col_g1, col_g2 = st.columns([2, 1])

with col_g1:
    fig_mc = go.Figure()
    for i in range(50):
        fig_mc.add_trace(go.Scatter(y=resultados[:, i], mode="lines", opacity=0.3, showlegend=False))

    st.plotly_chart(fig_mc,use_container_width=True)

with col_g2:

    precios_finales = resultados[-1, :]
    fig_dist = px.histogram(precios_finales, nbins=30, title="Distribución Final")

    st.plotly_chart(fig_dist, use_container_width=True)

# INFORME DE RIESGO

prob_p = (np.sum(precios_finales < monto) / len(precios_finales)) * 100
var_95 = (np.percentile(precios_finales, 5) - monto)

st.subheader("Informe de Resiliencia")
col_r1, col_r2 = st.columns(2)

with col_r1:

    if prob_p > 40:
        st.error(f"RIESGO CRÍTICO: {prob_p:.1f}%")

    elif prob_p > 20:
        st.warning(f"RIESGO MEDIO: {prob_p:.1f}%")

    else:
        st.success(f"RIESGO BAJO: {prob_p:.1f}%")

with col_r2:

    st.subheader("Interpretación")
    st.write(f"Volatilidad ajustada: {vol_sim:.2%}")
    st.write(f"VaR 95%: ${abs(var_95):,.2f}")

# EXPORTAR PDF

st.divider()
st.subheader("Exportar Resultados")

pdf_bytes = generar_pdf(nombre, perfil, score, monto, p_ret_hist, p_vol_hist, nombre_evento, prob_p, var_95)

st.download_button(    label="📄 Descargar PDF", data=pdf_bytes, file_name=f"Reporte_{nombre}.pdf", mime="application/pdf")











































































































































