# -*- coding: utf-8 -*-
"""ESCENARIOS_DE_INVERSIÓN_DESCUBRIENDO_TU_PERFIL_INVERSOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/alejocast2511/LENGUAJE-DE-PROGRAMACION-DCS/blob/main/ESCENARIOS_DE_INVERSION_DESCUBRIENDO_TU_PERFIL_INVERSOR.ipynb
"""

# -*- coding: utf-8 -*-
"""
“En la simulación de portafolios de inversión, el verdadero éxito financiero consiste en optimizar la rentabilidad asumiendo solo el riesgo necesario, evidenciando que la estrategia fundamentada supera siempre a la especulación.”

"""

import streamlit as st
import yfinance as yf
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

from datetime import datetime
from io import StringIO

st.set_page_config(layout="wide", page_title="Simulador Monte Carlo - Portafolios")

#  TIKERS

GRUPOS_PREDEFINIDOS = {
    "Conservador": ["BND", "VIG", "PG", "KO"],          # bonos/ETF defensivo + blue chips 
    "Moderado": ["SAN.MC", "BBVA.MC", "IBE.MC", "REP.MC"],  # bancos/energia 
    "Arriesgado": ["TSLA", "NVDA", "GOOGL", "AAPL"]         # tecnología / alto beta
}

DIAS_ANIO = 252


#  Funciones utilitarias


def descargar_precios(tickers, start_date, end_date, intervalo="1d"):
    
    if len(tickers) == 0:
        return pd.DataFrame()
    data = yf.download(tickers, start=start_date, end=end_date, interval=intervalo, progress=False, auto_adjust=True)
    
    if isinstance(data, pd.DataFrame) and "Close" in data.columns:
        data = data["Close"]
    if isinstance(data, pd.Series):
        data = data.to_frame()
    data = data.dropna(how="all", axis=1)
    return data

def retornos_log(precios):
    
    return np.log(precios / precios.shift(1)).dropna()

def estadisticas_retornos(retornos, rf=0.0, dias_anio=DIAS_ANIO):
    
    mu = retornos.mean() * dias_anio
    sigma = retornos.std() * np.sqrt(dias_anio)
    sharpe = (mu - rf) / sigma.replace(0, np.nan)
    return mu, sigma, sharpe

def simular_gbm_multivar(ultimos_precios, retornos_log_diarios, dias_sim, n_sim, seed=None):
    
    np.random.seed(seed)
    tickers = list(ultimos_precios.index)
    m = len(tickers)
    # medias y covarianza diaria (sobre retornos log)
    mu_d = retornos_log_diarios.mean().values        
    cov_d = retornos_log_diarios.cov().values        
    # Vars diarias
    var_d = np.diag(cov_d)                           
    dt = 1.0  
    try:
        L = np.linalg.cholesky(cov_d)
    except np.linalg.LinAlgError:
        
        jitter = 1e-8
        cov_d_jitter = cov_d + np.eye(m) * jitter
        L = np.linalg.cholesky(cov_d_jitter)
    
    rand = np.random.normal(size=(dias_sim, n_sim, m))
   
    correlated = rand @ L.T
    
    drift = (mu_d - 0.5 * var_d) 
    sqrt_dt = 1.0  
    logS0 = np.log(ultimos_precios.values)  
    pasos = np.zeros((dias_sim + 1, n_sim, m))
    pasos[0, :, :] = logS0 
    
    for t in range(1, dias_sim + 1):
      
        incremento = drift * dt + correlated[t-1] * sqrt_dt
        
        pasos[t] = pasos[t-1] + incremento
   
    precios_sim = np.exp(pasos) 
    
    fechas = pd.bdate_range(start=datetime.today(), periods=dias_sim + 1)
    
    return precios_sim, fechas, tickers
def construir_valor_portafolio(precios_sim_array, tickers, pesos):
    """
    Calcula el valor diario del portafolio a partir de las simulaciones de precios y los pesos de cada activo.
    precios_sim_array: ndarray con forma (dias+1, n_sim, n_activos)
    tickers: lista con los nombres de los activos
    pesos: array con los pesos (n_activos,)
    """
    # Verificar dimensiones
    n_dias, n_sim, n_activos = precios_sim_array.shape
    if len(pesos) != n_activos:
        raise ValueError(
            f"El número de pesos ({len(pesos)}) no coincide con el número de activos ({n_activos})"
        )

    # Cálculo del valor del portafolio
    port_vals = np.tensordot(precios_sim_array, pesos, axes=([2], [0]))  # (dias+1, n_sim)

    return port_vals  

#  Interfaz Streamlit

st.title("ESCENARIOS DE INVERSIÓN: DESCUBRE TU PERFIL INVERSOR.")
st.markdown("Responda la encuesta para determinar su perfil inversor y el portafolio de activos en el cual invertir.")

# Sidebar - encuesta
with st.sidebar:
    st.header("Perfil del inversor")

    #Datos del usuario
    edad = st.number_input("Edad", min_value=16, max_value=100, value=18)
    horizonte = st.selectbox("Horizonte de inversión", ["Corto (<=1 año)", "Medio (1-5 años)", "Largo (>5 años)"])
    experiencia = st.selectbox("Experiencia en inversiones", ["Ninguna", "Básica", "Intermedia", "Avanzada"])
    tolerancia = st.slider("Tolerancia al riesgo (1 conservador - 10 agresivo)", 1, 10, 5)
    st.markdown("---")
    st.header("Parámetros de simulación")
    monto_inversion = st.sidebar.number_input("Monto total a invertir (USD):", min_value=1000.0, value=5000.0, step=1000.0, format="%.2f",)
    st.sidebar.write(f"Monto ingresado: **${monto_inversion:,.2f} USD**")
    n_sim = st.number_input("Número de simulaciones", min_value=100, max_value=10000, value=2000, step=100)
    dias_sim = st.number_input("Horizonte simulación (días hábiles)", min_value=21, max_value=2520, value=252)
    rf = st.number_input("Tasa libre de riesgo anual (decimal)", min_value=0.0, max_value=0.05, value=0.0, step=0.001)
    intervalo = st.selectbox("Frecuencia histórica", ["1d", "1wk", "1mo"], index=0)
    start_date = st.date_input("Fecha inicio histórica", value=pd.to_datetime("2021-01-01"))
    end_date = st.date_input("Fecha fin histórica", value=pd.to_datetime(datetime.today().date()))
    seed = st.number_input("Semilla aleatoria (opcional, 0 = aleatorio)", min_value=0, value=0, step=1)
    st.markdown("---")

# Clasificación del perfil inversor ponderado
puntaje = 0

# Edad: los más jóvenes tienden a asumir más riesgo
if edad < 30:
    puntaje += 2
elif edad < 50:
    puntaje += 1

# Horizonte: largo plazo = mayor capacidad de riesgo
if "Largo" in horizonte:
    puntaje += 2
elif "Medio" in horizonte:
    puntaje += 1

# Experiencia: más conocimiento = más disposición al riesgo
niveles_exp = {"Ninguna": 0, "Básica": 1, "Intermedia": 2, "Avanzada": 3}
puntaje += niveles_exp[experiencia]

# Tolerancia (ponderada)
puntaje += tolerancia / 2  # escala de 1 a 10 → 0.5 a 5

# Determinar perfil
if puntaje <= 5:
    perfil = "Conservador"
elif puntaje <= 8:
    perfil = "Moderado"
else:
    perfil = "Arriesgado"

st.subheader(f"Perfil estimado: **{perfil}**")

# selección/edición de tickers
st.subheader("Selección de activos y pesos")
col1, col2 = st.columns([2, 1])
with col1:
    grupo = st.selectbox("Grupo de activos sugerido", list(GRUPOS_PREDEFINIDOS.keys()), index=list(GRUPOS_PREDEFINIDOS.keys()).index(
        "Conservador" if perfil=="Conservador" else ("Moderado" if perfil=="Moderado" else "Arriesgado")
    ))
    st.write("Tickers sugeridos:", ", ".join(GRUPOS_PREDEFINIDOS[grupo]))
    tickers_input = st.text_input("Edita tickers (coma separada) o deja sugeridos", value=", ".join(GRUPOS_PREDEFINIDOS[grupo]))
    tickers = [t.strip() for t in tickers_input.split(",") if t.strip() != ""]
with col2:
    st.write("Asigne pesos (deje 0 para usar igualitarios)")
    pesos = []
    default_w = 1.0 / len(tickers) if len(tickers) > 0 else 0
    for t in tickers:
        w = st.number_input(f"Peso {t}", min_value=0.0, max_value=1.0, value=float(round(default_w, 3)), step=0.01, key=f"w_{t}")
        pesos.append(w)
    suma = sum(pesos) if len(pesos) > 0 else 0
    if suma == 0 and len(pesos) > 0:
        pesos = [1.0 / len(pesos)] * len(pesos)
    else:
        pesos = [p / suma for p in pesos] if suma > 0 else pesos
    st.write("Pesos normalizados:", {tickers[i]: round(pesos[i], 4) for i in range(len(tickers))})

st.markdown("---")

# boton ejecutar
if st.button("Ejecutar simulación"):
    if len(tickers) == 0:
        st.error("Ingrese al menos un ticker válido.")
    else:
        if seed == 0:
            seed_val = None
        else:
            seed_val = int(seed)
        with st.spinner("Descargando precios..."):
            precios = descargar_precios(tickers, start_date.isoformat(), end_date.isoformat(), intervalo)
        if precios.empty:
            st.error("No se obtuvieron precios. Revise tickers / fechas / conexión.")
        else:
            
            if isinstance(precios, pd.Series):
                precios = precios.to_frame()
            precios = precios.dropna(axis=1, how="all")
            st.success("Precios descargados")      
                      
            st.subheader("Serie histórica de precios")
            fig_p = px.line(precios, x=precios.index, y=precios.columns, labels={"value": "Precio", "index": "Fecha"}, title="Precios ajustados")
            st.plotly_chart(fig_p, use_container_width=True)
        
            rlog = retornos_log(precios)
            mu_ann, sigma_ann, sharpe = estadisticas_retornos(rlog, rf=rf)
            stats_df = pd.DataFrame({"Mu (ann)": mu_ann, "Sigma (ann)": sigma_ann, "Sharpe": sharpe})
            st.subheader("Estadísticas históricas (anualizadas)")
            st.dataframe(stats_df.style.format("{:.4f}"))
            
            st.subheader("Heatmap de correlaciones (retornos diarios)")
            corr = rlog.corr()
            fig_corr = px.imshow(corr, text_auto=True, title="Matriz de correlaciones")
            st.plotly_chart(fig_corr, use_container_width=True)
           
            st.subheader("Retornos acumulados (índice = 1)")
            precios_norm = precios / precios.iloc[0]
            fig_norm = px.line(precios_norm, x=precios_norm.index, y=precios_norm.columns, title="Crecimiento relativo")
            st.plotly_chart(fig_norm, use_container_width=True)
            
            st.subheader("Diagrama riesgo-retorno (activos)")
            fig_rr = px.scatter(x=sigma_ann.values, y=mu_ann.values, text=sigma_ann.index, labels={"x": "Sigma (ann)", "y": "Mu (ann)"}, title="Riesgo vs Retorno")
            for i, t in enumerate(sigma_ann.index):
                fig_rr.add_annotation(x=sigma_ann.values[i], y=mu_ann.values[i], text=t, showarrow=False)
            st.plotly_chart(fig_rr, use_container_width=True)
            
            st.subheader("Simulación Monte Carlo (GBM multivariante)")
            with st.spinner("Corriendo simulación Monte Carlo..."):
                precios_sim_array, fechas_sim, tickers_sim = simular_gbm_multivar(
                    ultimos_precios=precios.iloc[-1],
                    retornos_log_diarios=rlog,
                    dias_sim=int(dias_sim),
                    n_sim=int(n_sim),
                    seed=seed_val
                )
                # construir portafolio
                pesos_arr = np.array(pesos)
                port_vals = construir_valor_portafolio(precios_sim_array, tickers_sim, pesos_arr)  # shape (dias+1, n_sim)
                # Escalar los valores simulados según el monto de inversión
                port_vals = port_vals * (monto_inversion / port_vals[0, 0])
            st.success("Simulación completa")

            # métricas finales y percentiles
            finales = port_vals[-1, :]  # valores finales por simulación
            valor_inicial = monto_inversion
            resumen = {
                "Valor inicial de la inversión": round(valor_inicial, 4),
                "Media final": float(np.mean(finales)),
                "Mediana final": float(np.median(finales)),
                "P10 final": float(np.percentile(finales, 10)),
                "P90 final": float(np.percentile(finales, 90))
            }
            st.subheader("Resumen estadístico (distribución final del portafolio)")
            st.write(resumen)

            # graficar evoluciones: muestras y percentiles
            st.subheader("Evolución simulada del valor del portafolio")
            muestras = min(10, int(n_sim))
            fig_evo = go.Figure()
            for i in range(muestras):
                fig_evo.add_trace(go.Scatter(x=fechas_sim, y=port_vals[:, i], mode="lines", line=dict(width=1), showlegend=False))
            p10 = np.percentile(port_vals, 10, axis=1)
            p50 = np.percentile(port_vals, 50, axis=1)
            p90 = np.percentile(port_vals, 90, axis=1)
            fig_evo.add_trace(go.Scatter(x=fechas_sim, y=p50, mode="lines", name="Mediana", line=dict(width=3)))
            fig_evo.add_trace(go.Scatter(x=fechas_sim, y=p10, mode="lines", name="P10", line=dict(dash="dash")))
            fig_evo.add_trace(go.Scatter(x=fechas_sim, y=p90, mode="lines", name="P90", line=dict(dash="dash")))
            fig_evo.update_layout(xaxis_title="Fecha", yaxis_title="Valor del portafolio")
            st.plotly_chart(fig_evo, use_container_width=True)

            # histograma del valor final
            st.subheader("Histograma del valor final del portafolio")
            fig_hist = px.histogram(finales, nbins=50, labels={"value": "Valor final"}, title="Distribución del valor final")
            st.plotly_chart(fig_hist, use_container_width=True)

            # métricas históricas del portafolio (usando retornos diarios)
            ret_port_hist = (precios.pct_change().dropna() @ pesos_arr)
            mu_port = ret_port_hist.mean() * DIAS_ANIO
            sigma_port = ret_port_hist.std() * np.sqrt(DIAS_ANIO)
            sharpe_port = (mu_port - rf) / (sigma_port if sigma_port != 0 else np.nan)
            st.subheader("Métricas históricas del portafolio")
            st.write({"Mu_port (ann)": round(mu_port, 4), "Sigma_port (ann)": round(sigma_port, 4), "Sharpe_port": round(sharpe_port, 4)})

            # comparación con benchmark opcional
            st.subheader("Comparación con benchmark")
            benchmark = st.text_input("Ticker benchmark (ej: ^GSPC)", value="^GSPC")
            if benchmark:
                try:
                    bench = descargar_precios([benchmark], start_date.isoformat(), end_date.isoformat(), intervalo)
                    if not bench.empty:
                        if isinstance(bench, pd.DataFrame):
                            bench_series = bench.squeeze()
                        else:
                            bench_series = bench
                        bench_norm = bench_series / bench_series.iloc[0]
                        port_hist = (precios_norm.values @ pesos_arr)
                        fig_b = go.Figure()
                        fig_b.add_trace(go.Scatter(x=precios_norm.index, y=port_hist, name="Portafolio histórico"))
                        fig_b.add_trace(go.Scatter(x=bench_norm.index, y=bench_norm.values, name=benchmark))
                        fig_b.update_layout(xaxis_title="Fecha", yaxis_title="Crecimiento")
                        st.plotly_chart(fig_b, use_container_width=True)
                except Exception as e:
                    st.write("No se pudo descargar benchmark:", e)

            # exportar simulación (CSV)
            st.subheader("Exportar resultados")
            # creamos DataFrame con columnas sim_0, sim_1, ...
            df_port_sims = pd.DataFrame(port_vals, index=fechas_sim, columns=[f"sim_{i}" for i in range(port_vals.shape[1])])
            csv_buf = df_port_sims.to_csv(index=True)
            st.download_button("Descargar simulaciones (CSV)", data=csv_buf, file_name="simulaciones_portafolio.csv", mime="text/csv")

            st.info("Simulación generada. Revisa supuestos: GBM, estimaciones históricas de mu/sigma y correlaciones.")

# ==========================
# === SECCIÓN FINAL: CÓDIGO QR PARA VOTAR ===
# ==========================

import qrcode
from io import BytesIO

st.markdown("---")
st.header("📲 Apoya este proyecto")

st.write("""
Gracias por explorar **Escenarios de Inversión: Descubriendo tu Perfil Inversor**.  
Tu opinión es clave para seguir mejorando y aprendiendo sobre programación y conocimiento financiero.  
Escanea el siguiente código QR y vota por este proyecto en el concurso.
""")

url_votacion = "https://itmconcurso.streamlit.app/?equipo=ITM2025-004"  

qr_img = qrcode.make(url_votacion)
buffer = BytesIO()
qr_img.save(buffer, format="PNG")

st.markdown("<div style='text-align: center;'>", unsafe_allow_html=True)
st.image(buffer.getvalue(), caption="Escanea con tu celular. Codigo equipo:ITM2025-004", use_container_width=False)
st.markdown("</div>", unsafe_allow_html=True)
