# -*- coding: utf-8 -*-
"""trabajosinnombrar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fyw3Erpo7HxnjrCPyLRDEGEEilyl9GYW
"""

"""
Proyecto: Análisis de portafolios de inversión por Simulación Monte Carlo

"""
!pip install yfinance streamlit pyngrok scipy pandas numpy matplotlib
# %%writefile app.py

# ==== 1 Importar librerías ====
import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from scipy.stats import norm
import sys
import subprocess
import threading
import time
import io
import math
from typing import List

# Configuración de página
st.set_page_config(page_title="ESCENARIOS DE INVERSIÓN: DESCUBRE TU PERFIL INVERSOR. ", layout="wide")

# ==========================================
# 1. CUESTIONARIO Y FILTRO DE CONOCIMIENTO
# ==========================================
st.title("ESCENARIOS DE INVERSIÓN: DESCUBRE TU PERFIL INVERSOR.")
with st.sidebar:
    st.header("👤 Perfil del Inversor")
    nombre = st.text_input("Nombre completo")
    edad = st.number_input("Edad", 18, 100, 25)
    monto = st.number_input("Cantidad a invertir (USD)", 1000, 1000000, 10000)
    tiempo = st.slider("Tiempo de inversión (Años)", 1, 10, 5)

    st.subheader("Filtro de Conocimiento")
    p1 = st.radio("Inflación: $100 al 2% con inflación del 3%, ¿compras más o menos?", ["Más", "Menos", "Igual"])
    p2 = st.radio("Riesgo-Retorno: Inversión garantizada 20% mensual sin riesgo es:", ["Muy probable", "Estafa/Error", "Normal"])
    p3 = st.radio("Diversificación: ¿Una sola acción es más segura que un ETF?", ["Sí", "No"])
    p4 = st.radio("Estadística: Retorno 10% y Volatilidad 25%, ¿puedo perder dinero?", ["Sí", "No"])

    # Lógica de Puntaje
    score = 0
    if p1 == "Menos": score += 1
    if p2 == "Estafa/Error": score += 1
    if p3 == "No": score += 1
    if p4 == "Sí": score += 1

    # Determinación de Perfil
    if score <= 1:
        perfil = "Conservadora"
        tickers_sugeridos = ["BND", "TIP", "GLD", "VIG"] # Bonos, Oro, Dividendos
    elif score <= 3:
        perfil = "Balanceada"
        tickers_sugeridos = ["SPY", "VEU", "BND", "VNQ"] # S&P500, Global, Inmuebles
    else:
        perfil = "Arriesgada"
        tickers_sugeridos = ["QQQ", "VWO", "BTC-USD", "SMH"] # Tech, Emergentes, Crypto

    st.success(f"Perfil Determinado: **{perfil}**")
    st.info(f"Nivel de conocimiento Financiero-estadistico: {score}/4")

# ==========================================
# 2. SELECCIÓN DE ACTIVOS Y DATOS
# ==========================================
st.header(f"💼 Portafolio Sugerido para Perfil {perfil}")
tickers_input = st.text_input("Activos (puedes editarlos separando por coma):", ",".join(tickers_sugeridos))
tickers = [t.strip() for t in tickers_input.split(",")]

@st.cache_data
def get_data(tickers):
    data = yf.download(tickers, start=datetime.now()-timedelta(days=1095))['Close']
    return data

data = get_data(tickers)
returns = data.pct_change().dropna()

# Estadísticas Anualizadas
mu = returns.mean() * 252
sigma = returns.std() * np.sqrt(252)
sharpe = mu / sigma

col1, col2 = st.columns(2)
with col1:
    st.subheader("📊 Estadísticas Históricas")
    stats_df = pd.DataFrame({"Retorno Anual (μ)": mu, "Volatilidad (σ)": sigma, "Eficiencia (Sharpe)": sharpe})
    st.table(stats_df)

with col2:
    st.subheader("🔥 Mapa de Correlaciones")
    fig_corr = px.imshow(returns.corr(), text_auto=True, color_continuous_scale='RdBu_r')
    st.plotly_chart(fig_corr, use_container_width=True)

# ==========================================
# 3. ESCENARIOS DE ESTRÉS
# ==========================================
st.divider()
st.header("☣️ Laboratorio de Stress Test")
st.write("Inyecta eventos globales para ver cómo reaccionaría tu portafolio:")

col_e1, col_e2, col_e3 = st.columns(3)
shock_mu = 0
shock_sigma = 1
shock_corr = 0

with col_e1:
    if st.button("🚨 Guerra Mundial"):
        shock_mu = -0.15
        shock_sigma = 2.0
        shock_corr = 0.5
        st.warning("Efecto: Caída en retornos y alta correlación.")

with col_e2:
    if st.button("🦠 Pandemia"):
        shock_mu = -0.10
        shock_sigma = 2.5
        st.warning("Efecto: Volatilidad extrema.")

with col_e3:
    if st.button("📉 Aranceles"):
        shock_mu = -0.05
        st.warning("Efecto: Reducción de retornos en exportación.")

# ==========================================
# 4. SIMULACIÓN MONTE CARLO (1 AÑO)
# ==========================================
# Pesos iguales por defecto
weights = np.array([1/len(tickers)] * len(tickers))
port_ret = np.sum(mu * weights) + shock_mu
port_vol = (np.sqrt(np.dot(weights.T, np.dot(returns.corr() + shock_corr, weights))) * np.mean(sigma)) * shock_sigma

simulaciones = 1000
dias = 252
last_price = monto

sim_results = np.zeros((dias, simulaciones))

for i in range(simulaciones):
    daily_rets = np.random.normal(port_ret/dias, port_vol/np.sqrt(dias), dias)
    sim_results[:, i] = last_price * (1 + daily_rets).cumprod()

# Visualización Monte Carlo
fig_sim = go.Figure()
for i in range(min(simulaciones, 50)): # Dibujar solo 50 líneas para fluidez
    fig_sim.add_trace(go.Scatter(y=sim_results[:, i], mode='lines', line=dict(width=1), opacity=0.3, showlegend=False))

st.subheader("📈 Proyección de Valor de Portafolio (1 Año)")
st.plotly_chart(fig_sim, use_container_width=True)

# ==========================================
# 5. DASHBOARD DE INTERPRETACIÓN
# ==========================================
st.divider()
st.header("📢 Narrativa de Resultados")

final_prices = sim_results[-1, :]
max_ganancia = np.max(final_prices) - monto
max_perdida = np.min(final_prices) - monto
prob_perder_mitad = (np.sum(final_prices < (monto * 0.5)) / simulaciones) * 100

c_inf1, c_inf2, c_inf3 = st.columns(3)

with c_inf1:
    st.metric("Máxima Ganancia Posible", f"${max_ganancia:,.2f}")
    st.write("**Traducción:** En el mejor de los casos, tu optimismo financiero se premia así.")

with c_inf2:
    color = "inverse" if prob_perder_mitad > 10 else "normal"
    st.metric("Riesgo de Ruina (Perder >50%)", f"{prob_perder_mitad}%")
    st.write("🟢 Bajo" if prob_perder_mitad < 5 else "🔴 CRÍTICO")

with c_inf3:
    st.metric("Incertidumbre (Volatilidad)", f"{port_vol*100:.2f}%")
    st.write(f"Tu Sharpe es {port_ret/port_vol:.2f}. Indica qué tan eficiente es tu riesgo.")

st.subheader("📋 Conclusión para el Semillero")
if prob_perder_mitad > 15:
    st.error(f"¡CUIDADO! El escenario de estrés muestra que hay un **{prob_perder_mitad}%** de probabilidad de perder más de la mitad de tu ahorro. Tu perfil '{perfil}' requiere activos de mayor calidad en este contexto.")
else:
    st.success("Tu portafolio muestra resiliencia ante los shocks inyectados. La diversificación está funcionando.")